version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: mini_mime
    versions:
    - 1.0.3
  - dependency-name: mimemagic
    versions:
    - 0.3.8
  - dependency-name: capybara
    versions:
    - 3.35.2
  - dependency-name: bootsnap
    versions:
    - 1.6.0
