language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
branches:
  only:
    - master
bundler_args: --no-deployment --path ./vendor/bundle
before_install:
  - gem update --system
  - gem --version
script: /home/travis/build/tigefa4u/tigefa/bin/build
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 1.9.3
notifications:
  email:
    on_success: never
    on_failure: never
