# os:
#  - linux
#  - osx
sudo: required
dist: trusty
language: ruby
cache: bundler
services:
  - docker
  - redis-server
rvm:
  - 2.4.4
#branches:
#  only:
#    - master
before_install:
  - gem install bundler --pre
  - gem update --system
script:
  - bundle exec rake test
addons:
  apt:
    packages:
      - docker-ce
matrix:
  fast_finish: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1048d1049fd1498d2313
  email: false
