language: ruby
rvm:
  - 2.3.1
branches:
  only:
    - master
script:
  - bundle exec rake test
matrix:
  fast_finish: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1048d1049fd1498d2313
  email:
    on_success: never
    on_failure: never
