platform:
  - x86
  - x64

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - git --version

build: off

cache:
  - vendor/bundle

test_script:
  - bundle config --local path vendor/bundle
  - bundle install
  - bundle exec rake test

environment:
  matrix:
    - ruby_version: "24"

matrix:
  fast_finish: true
  allow_failures:
    - ruby_version: "24"
    
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/ad9d237e4e494d7f8b66
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
