# platform:
#   - x86
#   - x64
image: Ubuntu2004
install:
#  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
#  - set PATH=C:\Ruby%ruby_version%\bin;C:\Program Files\7-Zip;C:\Program Files\AppVeyor\BuildAgent;C:\Program Files\Git\cmd;C:\Windows\system32;C:\Program Files;C:\Windows
  - ruby --version
  - gem --version
  - git --version

build: off

cache:
  - vendor/bundle

test_script:
  - gem install bundler
  - bundle config --local path vendor/bundle
  - bundle install --jobs=9
  - bundle exec rake test

environment:
  matrix:
    - ruby_version: "26"
#    - ruby_version: "27"

matrix:
  fast_finish: true
  allow_failures:
    - ruby_version: "26"
#    - ruby_version: "27"
    
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/ad9d237e4e494d7f8b66
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
