version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install and Update Packages
          command: |
            echo 'Asia/Jakarta' > /etc/timezone
            export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
            gem install bundler
            bundle install
      - run:
          name: Test
          command: |
            bundle exec rake test
