name: No Response

# Both `issue_comment` and `scheduled` event types are required for this Action
# to work properly.
on:
  issue_comment:
    types: [created]
  schedule:
    - cron: '0 4 * * *'
jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          responseRequiredLabel: more-information-needed
